=== nafizUrRhmn/soap/src/main/resources/finger.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="handData">

        <xs:complexType>

            <xs:sequence>

                <xs:element name="head">

                    <xs:complexType>

                        <xs:sequence>

                            <xs:element name="handInfo" type="xs:positiveInteger"/>

                            <xs:element name="gender" type="xs:string"/>

                        </xs:sequence>

                    </xs:complexType>

                </xs:element>

                <xs:element name="body">

                    <xs:complexType>

                        <xs:sequence>

                            <xs:element name="fingers">

                                <xs:complexType>

                                    <xs:sequence>

                                        <xs:element name="finger" maxOccurs="unbounded">

                                            <xs:complexType>

                                                <xs:sequence>

                                                    <xs:element name="fingerName" type="xs:positiveInteger"/>

                                                    <xs:element name="fingerData" type="xs:string"/>

                                                </xs:sequence>

                                                <xs:attribute name="id" type="xs:integer" use="required"/>

                                            </xs:complexType>

                                        </xs:element>

                                    </xs:sequence>

                                </xs:complexType>

                            </xs:element>

                        </xs:sequence>

                    </xs:complexType>

                </xs:element>

            </xs:sequence>

        </xs:complexType>
    </xs:element>
</xs:schema>

=== nafizUrRhmn/soap/src/main/resources/finger.xml
<handData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="finger.xsd">

    <head>

        <handInfo>-23</handInfo>

        <gender>Male</gender>

    </head>



    <body>

        <fingers>

            <finger id="1">

                <fingerName>-6</fingerName>

                <fingerData>ABCDE</fingerData>

            </finger>



            <finger id="2">

                <fingerName>LeftIndexFinger</fingerName>

                <fingerData>FGHIJ</fingerData>

            </finger>



            <finger id="3">

                <fingerName>LeftMiddleFinger</fingerName>

                <fingerData>KLMNO</fingerData>

            </finger>



            <finger id="4">

                <fingerName>LeftRingFinger</fingerName>

                <fingerData>PQRST</fingerData>

            </finger>



            <finger id="5">

                <fingerName>LeftLittleFinger</fingerName>

                <fingerData>UVWXYZ</fingerData>

            </finger>

        </fingers>

    </body>

</handData>
